### ISSUE TITLE
mbed test fails on K64 / IAR

### ISSUE THREAD

**Issue by Alex-EEE** [ARMmbed/sd-driver#103]
Using IAR and a K64 board, the "Directory failures" tests fail with mbed os 5.9.2.  I think these tests were passing with 5.8.x?  But I'm not sure if "Directory failures" are new tests b/c I also just updated our copy of sd-driver

test case: 'Directory failures' .............................................................. FAIL in 0.12 sec

**Comment by deepikabhavnani** [comment]
Test failure with Mbed OS 5.9 and higher is related to https://github.com/ARMmbed/mbed-os/pull/6336, 
will fix the test to check update error codes.

**Comment by deepikabhavnani** [comment]
Issue is fixed and merged to master, hence closing.
