### ISSUE TITLE
mbed_app.json -> mbed_lib.json

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/sd-driver#11]
Should the sd-driver define a mbed_lib.json instead of the app example? 
No one wants contaminate their shorter mbed_app.json with this many pin definitions, those should come either via here (or better yet, have the mbed os pin define stuff sorted out).

**Comment by JanneKiiskila** [comment]
See https://github.com/ARMmbed/sd-driver/pull/13

**Comment by deepikabhavnani** [comment]
@JanneKiiskila Can we close this?

**Comment by JanneKiiskila** [comment]
Yes.
