### ISSUE TITLE
Deprecation note - moved to Mbed OS

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/sd-driver#112]
We should probably update README.md to include note about code being moved into Mbed-OS since 5.10 release and further updates/development will happen inside the Mbed OS repository?

**Comment by deepikabhavnani** [comment]
Please review - https://github.com/ARMmbed/sd-driver/pull/111

**Comment by JanneKiiskila** [comment]
Yep, left comments - this can be closed.
