### ISSUE TITLE
Readme.MD to include info how to run the tests

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/sd-driver#12]
Could we add some instructions how to run the test suite? It doesn't compile out of the box, you need to do something if you want to run them manually?

**Comment by deepikabhavnani** [comment]
Below two sections are update in PR #32. Let us know if test does not compile out of box for new version of driver.
1. Build the mbed OS Test Cases
2. Run the POSIX File Test Case

**Comment by deepikabhavnani** [comment]
Closing it, feel free to open if required.
