### ISSUE TITLE
Eliminate or replace wait_ms() instances

### ISSUE THREAD

**Issue by saedelman** [ARMmbed/sd-driver#24]
Eliminate or otherwise replace wait_ms() instances with Thread::wait() 

wait_ms() does a busy wait which is wasteful when dealing with multiple threads. When using an NRF52_DK target calling wait_ms() from multiple threads causes application hang. Replacing these occurrences with Thread::wait() solves this issue.

**Comment by deepikabhavnani** [comment]
@saedelman - SD driver is updated. Can you please verify if with NRF52_DK?

**Comment by saedelman** [comment]
@deepikabhavnani - confirmed.
