### ISSUE TITLE
SDBlockDevice Example Application doesn't test SD Card

### ISSUE THREAD

**Issue by ersatzavian** [ARMmbed/sd-driver#38]
The example code in the "[SDBlockDevice Example Application](https://github.com/ARMmbed/sd-driver/blob/master/README.md#sdblockdevice-example-application)" section of the readme does not memset the buffer between writing to the SD card and reading it back, so it will appear to work even if the SD card is not present or is not working properly.

**Comment by deepikabhavnani** [comment]
Update on PR #32 
No need of memset if error handling is done properly

**Comment by deepikabhavnani** [comment]
Closing it, feel free to open if required.
