### ISSUE TITLE
"BlockDevice.h" No such file or directory

### ISSUE THREAD

**Issue by mcprakash** [ARMmbed/sd-driver#45]
PFA the link to the snapshot of the online mbed compiler.

Please help me out. 

Thanks
![screenshot from 2017-07-25 11-43-54](https://user-images.githubusercontent.com/8052668/28588277-ed90af58-712e-11e7-901e-96b2e4b19888.png)

**Comment by deepikabhavnani** [comment]
mbed-os\features\filesystem\bd\BlockDevice.h is part of "mbed-os". Please import mbed-os as well

**Comment by deepikabhavnani** [comment]
@mcprakash - Hope that helped in resolving issue. Closing it feel free to reopen if required.
