### ISSUE TITLE
sd-driver does not work when MBED_CONF_RTOS_PRESENT=0

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/sd-driver#76]
because 
https://github.com/ARMmbed/sd-driver/blob/master/SDBlockDevice.cpp#L151-L157

when `MBED_CONF_RTOS_PRESENT=0` the mbed_lib_rev version is reported instead of mbed-os version.

But the sd-blockdevice does work without rtos.

Also the error https://github.com/ARMmbed/sd-driver/blob/master/SDBlockDevice.cpp#L153 shows the wrong version required. but that is secondary.

**Comment by deepikabhavnani** [comment]
Closing as fix is merged in master branch.
