### ISSUE TITLE
Add support for LPC1768 Expresso

### ISSUE THREAD

**Issue by ralphrmartin** [ARMmbed/sd-driver#82]
Please add support for the LPC1768 Expresso Board by including the following lines in mbed_lib.json. This is worth doing as the LPC1768 Expresso board is widely used for teaching etc.:

`        "LPC1768": {`
`             "SPI_MOSI": "p5",`
`             "SPI_MISO": "p6",`
`             "SPI_CLK":  "p7",`
`             "SPI_CS":   "p8"`
`        },`
`

**Comment by geky** [comment]
Does this look good to you?
https://github.com/ARMmbed/sd-driver/pull/83/files

**Comment by ralphrmartin** [comment]
Yes, good.
