### ISSUE TITLE
Seek test failing on K66F/GCC

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/sd-driver#84]
All other tests pass except for the seek test.

```
mbedgt: test suite report:
+--------------+---------------+---------------------------------+--------+--------------------+-------------+
| target       | platform_name | test suite                      | result | elapsed_time (sec) | copy_method |
+--------------+---------------+---------------------------------+--------+--------------------+-------------+
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | FAIL   | 65.13              | default     |
+--------------+---------------+---------------------------------+--------+--------------------+-------------+
mbedgt: test suite results: 1 FAIL
mbedgt: test case report:
+--------------+---------------+---------------------------------+----------------------------+--------+--------+---------+--------------------+
| target       | platform_name | test suite                      | test case                  | passed | failed | result  | elapsed_time (sec) |
+--------------+---------------+---------------------------------+----------------------------+--------+--------+---------+--------------------+
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Boundary seek and write    | 0      | 0      | SKIPPED | 0.0                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Large dir seek             | 0      | 0      | SKIPPED | 0.0                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Large file seek            | 0      | 0      | SKIPPED | 0.0                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Large file seek and write  | 0      | 0      | SKIPPED | 0.0                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Out-of-bounds seek         | 0      | 0      | SKIPPED | 0.0                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Seek tests                 | 1      | 0      | OK      | 49.48              |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Simple dir seek            | 0      | 1      | FAIL    | 0.06               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Simple file seek           | 0      | 0      | SKIPPED | 0.0                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek | Simple file seek and write | 0      | 0      | SKIPPED | 0.0                |
+--------------+---------------+---------------------------------+----------------------------+--------+--------+---------+--------------------+
mbedgt: test case results: 1 FAIL / 7 SKIPPED / 1 OK
mbedgt: completed in 65.32 sec
mbedgt: exited with code 1
```

**Comment by deepikabhavnani** [comment]
+--------------+---------------+-------------------------------------+----------------------------------------------------------------------------------------+--------+--------+--------+--------------------+
| target       | platform_name | test suite                          | test case                                                                              | passed | failed | result | elapsed_time (sec) |
+--------------+---------------+-------------------------------------+----------------------------------------------------------------------------------------+--------+--------+--------+--------------------+
| K66F-GCC_ARM | K66F          | sd-driver-tests-block_device-basic  | Testing read write random blocks                                                       | 1      | 0      | OK     | 6.94               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_00: fopen()/fgetc()/fprintf()/fclose() test.                          | 1      | 0      | OK     | 0.17               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_01: fopen()/fseek()/fclose() test.                                    | 1      | 0      | OK     | 0.25               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_03: tmpnam() test.                                                    | 1      | 0      | OK     | 0.07               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_04: fileno() test.                                                    | 1      | 0      | OK     | 0.09               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_05: opendir() basic test.                                             | 1      | 0      | OK     | 0.65               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_06: fread()/fwrite() file to sdcard.                                  | 1      | 0      | OK     | 0.14               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_07: sdcard fwrite() file test.                                        | 1      | 0      | OK     | 0.17               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_08: FATFileSystem::read()/write() test.                               | 1      | 0      | OK     | 4.3                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_09: POSIX FILE API fread()/fwrite() test.                             | 1      | 0      | OK     | 4.86               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-basic    | FSFAT_BASIC_TEST_10: ChanFS read()/write()) test.                                      | 1      | 0      | OK     | 4.15               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Directory creation                                                                     | 1      | 0      | OK     | 0.41               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Directory failures                                                                     | 1      | 0      | OK     | 0.08               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Directory iteration                                                                    | 1      | 0      | OK     | 0.07               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Directory remove                                                                       | 1      | 0      | OK     | 0.33               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Directory rename                                                                       | 1      | 0      | OK     | 3.02               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Directory tests                                                                        | 1      | 0      | OK     | 9.16               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | File creation                                                                          | 1      | 0      | OK     | 0.08               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Multi-block directory                                                                  | 1      | 0      | OK     | 50.3               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Nested directories                                                                     | 1      | 0      | OK     | 1.13               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-dirs     | Root directory                                                                         | 1      | 0      | OK     | 0.07               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Block Size file test                                                                   | 1      | 0      | OK     | 0.53               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Dir check                                                                              | 1      | 0      | OK     | 0.06               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | File tests                                                                             | 1      | 0      | OK     | 9.15               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Large file test                                                                        | 1      | 0      | OK     | 7.81               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Medium file test                                                                       | 1      | 0      | OK     | 0.35               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Multiple block size file test                                                          | 1      | 0      | OK     | 0.71               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Non-overlap check                                                                      | 1      | 0      | OK     | 3.19               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Simple file test                                                                       | 1      | 0      | OK     | 0.13               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-files    | Small file test                                                                        | 1      | 0      | OK     | 0.14               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_01: fopen()/fwrite()/fclose() directories/file in multi-dir filepath. | 1      | 0      | OK     | 2.75               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_02: fopen(r) pre-existing file try to write it.                       | 1      | 0      | OK     | 0.16               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_03: fopen(w+) pre-existing file try to write it.                      | 1      | 0      | OK     | 0.3                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_04: fopen() with a filename exceeding the maximum length.             | 1      | 0      | OK     | 0.1                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_06: fopen() with bad filenames (minimal).                             | 1      | 0      | OK     | 0.1                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_07: fopen()/errno handling.                                           | 1      | 0      | OK     | 0.08               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_08: ferror()/clearerr()/errno handling.                               | 1      | 0      | OK     | 0.09               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_09: ftell() handling.                                                 | 1      | 0      | OK     | 0.11               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_10: remove() test.                                                    | 1      | 0      | OK     | 0.59               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_11: rename().                                                         | 1      | 0      | OK     | 0.88               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_12: opendir(), readdir(), closedir() test.                            | 1      | 0      | OK     | 1.5                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_13: mkdir() test.                                                     | 1      | 0      | OK     | 0.5                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_14: stat() test.                                                      | 1      | 0      | OK     | 0.6                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_15: format() test.                                                    | 1      | 0      | OK     | 9.19               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-fopen    | FSFAT_FOPEN_TEST_16: write/check n x 25kB data files.                                  | 1      | 0      | OK     | 37.73              |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-parallel | File tests                                                                             | 1      | 0      | OK     | 9.15               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-parallel | Filesystem access from multiple threads                                                | 1      | 0      | OK     | 0.66               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Boundary seek and write                                                                | 1      | 0      | OK     | 0.37               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Large dir seek                                                                         | 1      | 0      | OK     | 0.17               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Large file seek                                                                        | 1      | 0      | OK     | 0.1                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Large file seek and write                                                              | 1      | 0      | OK     | 0.15               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Out-of-bounds seek                                                                     | 1      | 0      | OK     | 0.11               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Seek tests                                                                             | 1      | 0      | OK     | 25.89              |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Simple dir seek                                                                        | 1      | 0      | OK     | 0.09               |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Simple file seek                                                                       | 1      | 0      | OK     | 0.1                |
| K66F-GCC_ARM | K66F          | sd-driver-tests-filesystem-seek     | Simple file seek and write                                                             | 1      | 0      | OK     | 0.12               |
+--------------+---------------+-------------------------------------+----------------------------------------------------------------------------------------+--------+--------+--------+--------------------+

**Comment by deepikabhavnani** [comment]
@marcuschangarm  - All the test on K66F were successful with sd-driver master and  mbed-os-5.7. 
Can you help in reproducing the failure (mbed-os version / sd-driver version)

**Comment by marcuschangarm** [comment]
I just re-ran the test using:

sd-driver: 10aac9f16207e81d0f231dfc9eef7ac88ad32c27
mbed-os: 91e6db1ea251ffcc973001ed90477f42fdca5751

same result.

**Comment by marcuschangarm** [comment]
Fix incoming: https://github.com/ARMmbed/mbed-os/pull/6363
